name: Auto Create Pull Requests

on:
  schedule:
    - cron: '0 * * * *' # Run every hour

jobs:
  create_pull_requests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Check for new pull requests and create corresponding pull requests
        env:
          BASE_REPO_OWNER: fproldan
          BASE_REPO_NAME: basetest
          FORK_REPO_OWNER: diamorafaela
          FORK_REPO_NAME: basetest
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python create_pull_requests.py
