name: Replicate Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  replicate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout base repository
        uses: actions/checkout@v2
        with:
          repository: fproldan/basetest
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ ssecrets.GITHUB_TOKEN }} # Provide a personal access token with read access to the base repository
        
      - name: Checkout forked repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }} # Provide a personal access token with write access to the forked repository

      - name: Apply Changes and Push to Forked Repository
        run: |
          # Configure git to use the forked repository as the origin
          git remote set-url origin https://github.com/${{ github.repository_owner }}/${{ github.repository }}

          # Fetch the branch associated with the pull request from the base repository
          git fetch origin ${{ github.event.pull_request.head.ref }}:${{ github.event.pull_request.head.ref }}

          # Checkout the branch associated with the pull request
          git checkout ${{ github.event.pull_request.head.ref }}

          # Push changes to a new branch in the forked repository
          git push origin HEAD:${{ github.event.pull_request.head.ref }}-replica
